### ISSUE TITLE
Edit task doen't work

### ISSUE THREAD

**Issue by atvirasvilnius** [taqueci/redmine_wysiwyg_editor#37] opened 2019-03-01 08:03 UTC
If you want to edit issuse you can't.

![screenshot_1](https://user-images.githubusercontent.com/12123428/53624478-1bc86180-3c09-11e9-8fa2-1c40a29fff70.jpg)

![screenshot_2](https://user-images.githubusercontent.com/12123428/53624532-49150f80-3c09-11e9-880d-77964684818c.jpg)

**Comment by taqueci** [comment] 2019-03-03 02:45
Hi @atvirasvilnius 

I can not reproduce the issue.
Please evaluate plugins one by one.

Note I had confirmed in the environment:

```
Environment:
  Redmine version                3.4.7.stable
  Ruby version                   2.3.4-p301 (2017-03-30) [x86_64-linux]
  Rails version                  4.2.11
  Environment                    development
  Database adapter               SQLite
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Bazaar                         2.7.0
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.12
  issue_charts                   2.0.0
  quick_add_issue                0.0.4
  recurring_tasks                2.0.0-pre
  redmine_agile                  1.4.8
  redmine_bitbucket              1.0.0
  redmine_checklists             3.1.14
  redmine_dmsf                   1.6.0
  redmine_drawio                 0.8.0
  redmine_gitlab_hook            0.2.2
  redmine_impersonate            1.0.0
  redmine_issue_templates        0.1.8
  redmine_lightbox2              0.4.3
  redmine_local_avatars          1.0.3
  redmine_pivot_table            0.0.6
  redmine_questions              1.0.0
  redmine_send_issue_reply_email 1.0.0
  redmine_wysiwyg_editor         0.3.3
  that_email_log                 0.0.2
  vault                          0.3.10
```

**Comment by TrumanRu** [comment] 2019-10-21 13:13
Same problem in modal dialog (div.modal) created by plugin 'easy_wbs'.

I think plugin 'redmine_wysiwyg_editor' can't distinguish activation state or missed activation in AJAX modal dialog.

**Comment by lcasanova78** [comment] 2021-04-13 12:44
I have the same problem in Redmine 4, description is not displayed and also the position of the rest of the fields is not configured.

**Comment by taqueci** [comment] 2021-04-16 13:13
Hi @lcasanova78 

Can you find any error messages in developer tool console?

**Comment by picman** [comment] 2021-05-03 12:18
I think that the problem is related to IE 11 on client side only. In the Console I see "Object soesn't support property or method 'prepend'".

**Comment by taqueci** [comment] 2021-05-03 13:37
Merged.
Thank you, @picman !

**Closed by taqueci** 2021-05-03 13:37 UTC
