### ISSUE TITLE
Edits disappear when using HTML Anchors

### ISSUE THREAD

**Issue by nanego** [taqueci/redmine_wysiwyg_editor#86] opened 2020-05-04 12:25 UTC
When we use anchors in issues or wikis, edits written in Visual Mode are not taken in account when we switch to the Textile tab.
These edits disappear and a JS error appears in our browser console.

Here is the error:
```
href: "#2"
m: null
TypeError: m is null     redmine_wysiwyg_editor.js:893:18
```

And the steps to reproduce:
1. Open new issue form
1. In Textile mode, enter this text in description field: [[#2]]
1. Switch to Visual tab
1. Select the '#2' link
1. Click on the icon to "edit link"
1. "Insert link" form appears. Click OK without modifying anything
1. Switch back to textile tab
⇒ the error appears in the console

Thank you for your help!

**Comment by taqueci** [comment] 2020-05-08 05:00
Hi @nanego 

Thank you for reporting the issue.

I have fixed error caused by a link to an anchor on the same page.  
Could you please try branch [issue/86](https://github.com/taqueci/redmine_wysiwyg_editor/tree/issue/86)?

**Comment by nanego** [comment] 2020-05-08 07:12
Thank you @taqueci. The fix works very well.

**Comment by taqueci** [comment] 2020-05-08 09:09
Hi @nanego 

Thank you for confirming.  
The commit has been merged into master branch.

**Closed by taqueci** 2020-05-08 09:09 UTC
Labels: bug
