### ISSUE TITLE
Pasting image does not work in "Document" 

### ISSUE THREAD

**Issue by SilverBut** [taqueci/redmine_wysiwyg_editor#67] opened 2019-09-24 08:48 UTC
Can be easily reproduced by create a documenation, switch to visual editor, and press Ctrl+V.

Here is the error log in console: 

```
edit:121 Uncaught ReferenceError: uploadAndAttachFiles is not defined
    at RedmineWysiwygEditor.uploader [as _attachmentUploader] (edit:121)
    at RedmineWysiwygEditor._pasteImage (redmine_wysiwyg_editor.js?1568924623:473)
    at RedmineWysiwygEditor._pasteEventHandler (redmine_wysiwyg_editor.js?1568924623:426)
    at zx.<anonymous> (redmine_wysiwyg_editor.js?1568924623:236)
    at Vg.c.fire (tinymce.min.js?1568924623:2)
    at zx.fire (tinymce.min.js?1568924623:2)
    at np (tinymce.min.js?1568924623:2)
    at Object.t (tinymce.min.js?1568924623:2)
    at C (tinymce.min.js?1568924623:2)
    at HTMLBodyElement.d (tinymce.min.js?1568924623:2)
﻿```

**Comment by SilverBut** [comment] 2019-09-24 08:51
Oh seems 0.8.0 is updated yesterday. I would update my local server and then came back. If it works, I will just close this issue.

**Comment by taqueci** [comment] 2019-10-24 04:21
Hi @SilverBut 

I close this issue.
If the issue is not solved, please reopen and tell me more detail.

**Closed by taqueci** 2019-10-24 04:21 UTC
